### ISSUE TITLE
research: 研究 Auth0 的 Java SDK，归纳第一版需要实现的接口和功能

### ISSUE THREAD

**Issue by gao-sun** [logto-io/java#4]

**Comment by xiaoyijun** [comment]
1. 基本数据配置 client_id, redirect_url, domain
2. 登录 支持传入回调（提供的参数 Scope 、 Scheme-待讨论）
3. 登出
4. 基本的用户信息、accessToken获取
5. 提供全局的管理器

**Comment by gao-sun** [comment]
主要目标是用户名密码登录

**Comment by xiaoyijun** [comment]
1. 支持通过Gradle引入Android SDK包
2. 支持WebView登入/登出流程
3. 用户基本信息的获取
4. 授权信息管理（授权信息、有效状态、本地存储与查询）
